# Sample workflow for building and deploying an Astro site to GitHub Pages
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Deploy Astro site to Pages

on:
  # Runs on pushes targeting the default branch
  #push:
    #branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  BUILD_PATH: "." # default value when not using subfolders
  # BUILD_PATH: subfolder

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          
      - name: Install dependencies
        run: deno install
        working-directory: ${{ env.BUILD_PATH }}
        
      - name: Build with Astro
        run: deno npm:astro build --allow-env
        working-directory: ${{ env.BUILD_PATH }}
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          personal_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_branch: 'dist'
